# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FixD' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for FixD
  pod 'iOSDropDown'
  pod 'Apollo', :git => 'https://github.com/apollographql/apollo-ios.git'
  pod 'SwiftKeychainWrapper'
end

